// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://dkmthdkrrdcctzxcpxsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrbXRoZGtycmRjY3R6eGNweHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODI5MjAsImV4cCI6MjA3NDg1ODkyMH0.C-n8q5E8uxFiSM9-9KIIMX9vAb1OlCrnIlHo2WiRBjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    db: {
      schema: "demo",
    },
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
